defaults:
  - _self_

seed: 0

task:
  xo_index: 0
  beta: 1.0
  name: "linear_gaussian"

flow:
  training_batch_size: 500


hydra:
  run:
    dir: ../../results/benchmark/ground_truths/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}
  sweep:
    dir: ../../results/benchmark/ground_truths/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}
    subdir: .
  job:
    chdir: True
  launcher:
    n_jobs: 30
