defaults:
  - _self_

seed: 0

training: 
  training_simulation_budget: 1000

algorithm:
  NPE:
    density_estimator: 'nsf'
  NLE:
    density_estimator: 'nsf'
  GBI:
    net_type: 'resnet'
    training_batch_size: 1000
    num_layers: 3
    num_hidden: 50    
    noise_level: 2.0
    n_augmented_x: 100
    max_epochs: 5000
    print_every_n: 20
    positive_constraint_fn: 'softplus'


task:
  num_simulations: 1000
  name: "linear_gaussian"
  xo_index: 0
  beta: 1.0

# net:
#   training_batch_size: 500
#   num_layers: 2
#   num_hidden: 50
#   net_type: ResNet
#   noise_level: 1.0


hydra:
  run:
    dir: ../../../results/benchmark/algorithms/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}
  sweep:
    dir: ../../../results/benchmark/algorithms/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}
    subdir: .
  job:
    chdir: True
