defaults:
  - _self_
  - algorithm: GBI

seed: 0
trained_inference_datetime: ???
n_samples: 10000

task:
  name: "uniform_1d"
  beta: 100
  xo_index: 0  
  is_specified: "specified"
  is_known: "known"


hydra:
  run:
    dir: ../../../results/benchmark/algorithms/${task.name}/${trained_inference_datetime}/${algorithm.name}/posterior_inference/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}_${task.is_specified}_${task.is_known}
  sweep:
    # Only sweep over beta for GBI
    dir: ../../../results/benchmark/algorithms/${task.name}/${trained_inference_datetime}/${algorithm.name}/posterior_inference/${now:%Y_%m_%d}__${now:%H_%M_%S}/
    subdir: beta_${task.beta}/obs_${task.xo_index}_${task.is_specified}_${task.is_known}
  job:
    chdir: True
