name: 'GBI'
net_type: 'resnet'
training_batch_size: 1000
num_layers: 3
num_hidden: 50
noise_level: 2.0
n_augmented_x: 100
max_epochs: 5000
n_epochs_convergence: 50
print_every_n: 20
positive_constraint_fn: 'softplus'