defaults:
  - _self_

seed: 0

task:
  xo_index: 0
  beta: 1.0
  name: null
  is_specified: 'specified'
  is_known: 'known'

flow:
  training_batch_size: 500

rejection:
  num_samples_to_find_max: 10000
  num_iter_to_find_max: 100
hydra:
  run:
    dir: ../../../results/benchmark/ground_truths/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}_${task.is_specified}_${task.is_known}
  sweep:
    dir: ../../../results/benchmark/ground_truths/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}_${task.is_specified}_${task.is_known}
    subdir: .
  job:
    chdir: True



# python run_uniform_1d.py -m task.xo_index=0,1,2,3,4,5,6,7,8,9 task.is_specified='specified','misspecified' task.is_known='known','unknown' task.beta=4,20,100 task.name=uniform_1d
# python run_two_moons.py -m task.xo_index=0,1,2,3,4,5,6,7,8,9 task.is_specified='specified','misspecified' task.is_known='known','unknown' task.beta=10,100,1000 task.name=two_moons