defaults:
  - _self_

seed: 0

task:
  xo_index: 0
  beta: 1.0
  name: null

flow:
  training_batch_size: 500

rejection:
  num_samples_to_find_max: 10000
  num_iter_to_find_max: 100
hydra:
  run:
    dir: ../../../results/benchmark/ground_truths/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}
  sweep:
    dir: ../../../results/benchmark/ground_truths/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}
    subdir: .
  job:
    chdir: True
