defaults:
  - _self_

seed: 0

task:
  name: null
  beta: 1
  xo_index: 0
  is_specified: specified
  is_known: known

flow:
  training_batch_size: 500

rejection:
  num_samples_to_find_max: 100
  num_iter_to_find_max: 100
  num_rej_samples: 5000

hydra:
  run:
    dir: ../../../results/benchmark/ground_truths/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/beta_${task.beta}/obs_${task.xo_index}_${task.is_specified}_${task.is_known}
  sweep:
    dir: ../../../results/benchmark/ground_truths/${task.name}/${now:%Y_%m_%d}__${now:%H_%M_%S}/
    subdir: beta_${task.beta}/obs_${task.xo_index}_${task.is_specified}_${task.is_known}
  sweeper:
    params:
        task.xo_index: 0,1,2,3,4,5,6,7,8,9
        task.is_specified: specified,misspecified
        task.is_known: known,unknown
  job:
    chdir: True


# betas:
# uniform_1d: 4, 20, 100
# two_moons: 10, 100, 1000
# linear_gaussian: 1, 10, 100
# gaussian_mixture: 10, 50, 250