defaults:
  - _self_  

algos: ['GBI','eGBI','NPE','NLE','ABC']


task:
  name: "uniform_1d"  
  xo_index: 0  
  is_specified: "specified"
  is_known: "known"

task:
  name: "uniform_1d"
  
gt_datetime: ???
inference_datetime: ???

hydra:
  run:
    dir: ./hydra_log/${now:%Y_%m_%d}__${now:%H_%M_%S}/
  job:
    chdir: False

